import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AdtraceWrapper } from './_providers/adtrace-provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdtraceWrapper>
          {children}
        </AdtraceWrapper>
      </body>
    </html>
  );
}
