import Head from 'next/head'
import { useAdtraceContext } from '../utils/adtrace'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const adtraceSdk = useAdtraceContext()
  return (
    <>
      <Head>
        <title>Adtrace SDK Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>Adtrace SDK Test</h3>
        <button
          onClick={()=> adtraceSdk.trackEvent({
            eventToken: 'qpw44u',
            revenue: 10,
            currency: 'IRR',
            callbackParams: [
              {key: 'key', value: 'value'},
              {key: 'foo', value: 'bar'}
            ]
          })}
          style={{fontSize: 18, padding: 15}}>
          test event
        </button>
      </main>
    </>
  )
}
